"""Английские переводы интерфейса телефона: словарь «русский текст → английский»."""

from gmagc_common import lang_en as _common  # noqa: F401 - общие переводы регистрируются при импорте
from gmagc_common.i18n import register

EN = {
    "Адрес ПК": "PC address",
    "192.168.1.5 или 192.168.1.5:8765": "192.168.1.5 or 192.168.1.5:8765",
    "Код доступа": "Access code",
    "Считать QR-код с ПК": "Scan the QR code from the PC",
    "Подключиться": "Connect",
    "Профили приборов": "Fixture profiles",
    "Настройки": "Settings",
    "Помощь": "Help",
    "О программе": "About",
    "Галерея": "Gallery",
    "Версия {VERSION}. Автор: {AUTHOR}": "Version {VERSION}. Author: {AUTHOR}",
    "Поддержать автора": "Support the author",
    "Telegram автора": "Author's Telegram",
    "Канал GMAGC": "GMAGC channel",
    "Подключитесь к ПК с запущенным GMAGC в той же сети Wi-Fi: наведите камеру на QR-код в его окне (подключение произойдёт само) или введите адрес и код вручную. Дальше наводите камеру на проекцию и снимайте — совпадения из библиотеки на ПК придут в ответ.": "Connect to a PC running GMAGC on the same Wi-Fi network: point the camera at the QR code in its window (it connects by itself) or enter the address and code manually. Then aim the camera at the projection and take a photo: the matches from the PC library come back as the answer.",
    "«Профили»: создание профиля прибора для grandMA2 и grandMA3 с нуля (режимы, каналы из шаблонов, диапазоны значений). Все правки сохраняются сразу. Кнопки «Поделиться» отправляют готовые файлы: JSON профиля, XML для grandMA3 и по одному XML на режим для grandMA2 (положите их в fixturetypes библиотеки MA3 или в importexport MA2 и импортируйте в пульте).": "“Profiles”: create a fixture profile for grandMA2 and grandMA3 from scratch (modes, channels from templates, value ranges). All edits are saved at once. The “Share” buttons send ready files: the profile JSON, an XML for grandMA3 and one XML per mode for grandMA2 (put them into the fixturetypes folder of the MA3 library or into the MA2 importexport folder and import them on the console).",
    "Наведите камеру на QR-код в приложении на ПК — считается автоматически (приближение и касание для фокуса помогают)": "Point the camera at the QR code in the PC app: it is read automatically (zoom and tapping to focus help)",
    "Фокус по точке недоступен": "Tap to focus is not available",
    "Готово к съёмке": "Ready to shoot",
    "Снять": "Shoot",
    "Выбрать фото": "Choose a photo",
    "Считать QR": "Scan QR",
    "Ввести вручную": "Enter manually",
    "Сменить ПК": "Change PC",
    "Повторить": "Retry",
    "Пока нет снимков в этой сессии": "No photos in this session yet",
    "Камера доступна только на телефоне (Android)": "The camera is available only on a phone (Android)",
    "Нет доступа к камере: разрешите его в настройках телефона": "No access to the camera: allow it in the phone settings",
    "Камера не найдена": "Camera not found",
    "Камера недоступна": "Camera unavailable",
    "Не удалось снять: {error}": "Could not take the photo: {error}",
    "Не удалось подготовить фото: {error}": "Could not prepare the photo: {error}",
    "Ошибка: {error}": "Error: {error}",
    "Ошибка поиска": "Search error",
    "Нажмите «Назад» ещё раз, чтобы выйти": "Press “Back” again to exit",
    "Последняя ошибка: {text}": "Last error: {text}",
    "Фото проекции": "Projection photo",
    "Фото": "Photo",
    "Найденная проекция": "Found projection",
    "ещё {count} {files}": "{count} more {files}",
    "Копировать путь": "Copy path",
    "Путь скопирован: {path}": "Path copied: {path}",
    "Снять ещё": "Shoot again",
    "Поделиться": "Share",
    "Нет подключения к ПК: подключитесь на главном экране и повторите.": "Not connected to a PC: connect on the main screen and try again.",
    "Введите адрес ПК, например 192.168.1.5 или 192.168.1.5:8765": "Enter the PC address, for example 192.168.1.5 or 192.168.1.5:8765",
    "Код доступа состоит из 8 символов (буквы и цифры), он показан в приложении на ПК": "The access code has 8 characters (letters and digits); it is shown in the PC app",
    "Ошибка подключения: {error}": "Connection error: {error}",
    "Подключено к ПК: {host}:{port}": "Connected to the PC: {host}:{port}",
    "Ошибка камеры: {error}": "Camera error: {error}",
    "Профиль не готов к отправке: {problems}": "The profile is not ready to send: {problems}",
    "{console}: папка не найдена, укажите её в настройках ПК-приложения": "{console}: folder not found, specify it in the PC app settings",
    "{console}: не удалось использовать папку ({detail})": "{console}: could not use the folder ({detail})",
    "Поддержать": "Support",
    "Позже": "Later",
    "Больше не показывать": "Do not show again",
    "Скачать": "Download",
    "Пропустить": "Skip",
    "Проверить обновления": "Check for updates",
    "Ошибка проверки обновлений: {error}": "Update check error: {error}",
    "Установлена последняя версия ({VERSION})": "The latest version is installed ({VERSION})",
    "Доступна версия {version} (у вас {VERSION})": "Version {version} is available (you have {VERSION})",
    "Проверяю обновления…": "Checking for updates…",
    "Не удалось открыть ссылку на загрузку: {error}": "Could not open the download link: {error}",
    "Нет профилей. Создайте первый.": "No profiles. Create the first one.",
    "Новый профиль": "New profile",
    "Режимов: {count}": "Modes: {count}",
    "Удалить «{title}»?": "Delete “{title}”?",
    "Да": "Yes",
    "Нет": "No",
    "Режим {number}": "Mode {number}",
    "{name} (копия)": "{name} (copy)",
    "Не удалось поделиться: {error}": "Could not share: {error}",
    "Профиль прибора": "Fixture profile",
    "Производитель": "Manufacturer",
    "Короткое имя": "Short name",
    "Мод": "Modes",
    "{name} ({count} кан.)": "{name} ({count} ch.)",
    "Дублировать": "Duplicate",
    "Удалить": "Delete",
    "Добавить режим": "Add a mode",
    "Отправить на ПК": "Send to PC",
    "Поделиться профилем (файл JSON)": "Share the profile (JSON file)",
    "Поделиться для grandMA3 (файл XML)": "Share for grandMA3 (XML file)",
    "Поделиться для grandMA2 (файлы XML режимов)": "Share for grandMA2 (XML files of the modes)",
    "Режим": "Mode",
    "Название режима": "Mode name",
    "Каналы": "Channels",
    "Добавить канал (шаблон)": "Add a channel (template)",
    "Новый диапазон": "New range",
    "Записано на ПК:": "Written on the PC:",
    "Пропущено: {item}": "Skipped: {item}",
    "От": "From",
    "До": "To",
    "Удалить диапазон": "Delete the range",
    "Название значения": "Value name",
    "Канал": "Channel",
    "Шаблон": "Template",
    "Название": "Name",
    "По умолчанию": "Default",
    "{bits} бит": "{bits} bit",
    "Диапазоны значений (0–255)": "Value ranges (0–255)",
    "Добавить диапазон": "Add a range",
    "В инструкции не найдена таблица каналов DMX. Снимите таблицу ближе и ровнее или выберите другой файл.": "No DMX channel table was found in the manual. Shoot the table closer and straighter, or pick another file.",
    "В этот режим": "Into this mode",
    "Новым режимом": "As a new mode",
    "Добавлено каналов: {count}": "Channels added: {count}",
    "Заполнить по инструкции": "Fill in from the manual",
    "Инструкция прибора (фото или PDF)": "Fixture manual (photo or PDF)",
    "Найдено в инструкции": "Found in the manual",
    "Не удалось прочитать файл: {error}": "Could not read the file: {error}",
    "Отметьте хотя бы один канал.": "Check at least one channel.",
    "Продолжение таблицы": "Table continuation",
    "Распознаю инструкцию на ПК, это может занять минуту…": "Recognizing the manual on the PC, this may take a minute…",
    "Снимите галочки с лишнего. Названия и диапазоны можно поправить после добавления.": "Uncheck what you do not need. Names and ranges can be edited after adding.",
    "диапазонов: {count}": "ranges: {count}",
    "Улучшить в облаке": "Improve in the cloud",
    "Распознать в облаке": "Recognize in the cloud",
    "Файл инструкции будет отправлен через ПК в облако Anthropic (Claude) для распознавания. Нужен ключ Anthropic в настройках ПК-приложения. Отправить?": "The manual file will be sent through the PC to the Anthropic (Claude) cloud for recognition. An Anthropic key must be set in the PC app settings. Send it?",
    "Отправить в облако": "Send to the cloud",
    "Отмена": "Cancel",
    "Добавление отменено.": "Adding cancelled.",
    "Отменить": "Undo",
    "Гобо из библиотеки": "Gobo from the library",
    "Имя гобо": "Gobo name",
    "Найти по фото": "Find by photo",
    "Ищу на ПК…": "Searching on the PC…",
    "Ничего не найдено.": "Nothing found.",
    "Ещё {count}: уточните запрос.": "{count} more: narrow the query.",
    "Гобо: {name}": "Gobo: {name}",
    "Убрать гобо": "Remove the gobo",
    "{console}: файл гобо «{detail}» не найден в библиотеке": "{console}: the gobo file “{detail}” was not found in the library",
    "Создан режим «{name}»: каналов {count}": "Mode “{name}” created: {count} channels",
    "Создано режимов: {count}": "Modes created: {count}",
    "Нечего добавлять: все режимы уже добавлены или ничего не отмечено.": "Nothing to add: all modes are already added or nothing is checked.",
    "Добавить все режимы новыми": "Add all modes as new",
    "Продолжить с прошлым результатом": "Continue with the previous result",
    "QR-код не от GMAGC: наведите камеру на код в приложении на ПК.": "This QR code is not from GMAGC: point the camera at the code in the PC app.",
    "Назад": "Back",
    "Нет связи с ПК": "No connection to the PC",
    "Сначала подключитесь к ПК": "Connect to the PC first",
    "Язык": "Language",
    "Результаты": "Results",
    "Нажмите на карточку, чтобы скопировать путь": "Tap a card to copy the path",
    "(без названия)": "(no name)",
    "(без производителя)": "(no manufacturer)",
    "Выбрать": "Choose",
    "Импорт профиля из файла (JSON)": "Import a profile from a file (JSON)",
    "Не удалось прочитать профиль: {error}": "Could not read the profile: {error}",
    "Открыть": "Open",
    "Профиль добавлен: {name}": "Profile added: {name}",
    "двоичные файлы недоступны: отправьте профиль на ПК": "binary files are not available: send the profile to the PC",
    "недоступно на этом устройстве": "not available on this device",
}

register("en", EN)
